FROM node:18.13.0

# Directorio de trabajo dentro del contenedor
WORKDIR /api

# Copia el archivo package.json
COPY ./platform/api/package.json ./

COPY ./platform/api/.env ./

# Instala las dependencias de la aplicación
RUN npm install

# Copia los archivos desde la ruta local al directorio de trabajo en el contenedor
COPY ./platform/api/dist ./dist

# Expone el puerto de la aplicación (si tu app corre en un puerto específico, como 3000)
EXPOSE 5500

CMD ["npm", "run", "start:prod"]
